#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_DIR=$(cd "$SCRIPT_DIR/../.." && pwd)
FRONTEND_DIR="$REPO_DIR/frontend"

require_yes() {
  if ! confirm "$1"; then
    warn "本阶段未通过。请先修复问题，再重新运行验收向导。"
    exit 1
  fi
}

banner "Campus Search UI v2 人工验收"

say "本向导只运行本地检查并提示你观察浏览器，不读取或保存 API key、Cookie、登录态、搜索请求、模型响应或页面内容。"
say "建议使用 Edge，并准备一个已登录的 CC98 或朵朵页面。真实检索会访问当前站点和已配置模型。"
pause "准备好后按 Enter 开始。"

stage "自动检查并构建扩展"
say "运行完整测试、类型检查、生产构建与扩展产物校验。"
(cd "$FRONTEND_DIR" && npm test && npm run typecheck && npm run build)
require_yes "以上自动检查全部通过？"

stage "重载扩展并打开站点"
say "请在 Edge 打开扩展管理页，启用开发人员模式，并重新加载本地扩展。"
open_url "edge://extensions"
step "如果尚未加载扩展，选择“加载解压缩的扩展”，目录为：$FRONTEND_DIR/dist"
step "重载后打开已登录的 CC98 或朵朵页面；向导不会检查或读取登录状态。"
open_url "https://www.cc98.org/"
step "确认页面右下角出现新的搜索启动按钮。若扩展仍显示旧版本，回扩展管理页再次重载并刷新站点。"
require_yes "扩展已从 frontend/dist 加载，且站点页面出现搜索入口？"

stage "检查搜索页与移动布局"
step "打开搜索面板，检查 Campus Search 顶栏、关闭按钮和“搜索 / 设置”紧凑标签。"
step "确认首次空态包含“搜索校园里的真实讨论”和三个示例：操作系统课程评价、微积分历年卷、紫金港租房讨论。"
step "点击一个示例：它应填入并聚焦搜索框，但不应自动发起搜索。"
step "在约 390px 宽的浏览器窗口中检查抽屉；确认无横向滚动、输入框与搜索按钮完整可见。之后恢复窗口大小。"
step "检查搜索入口约 48px、绿色、无通知点；面板头部固定，面板内容区域独立滚动。"
require_yes "搜索页和窄窗口布局均符合预期？"

stage "检查设置、隐私与折叠区"
step "切换到“设置”，确认模型、检索、排序、隐私四组存在，数值控件为紧凑步进器。"
step "检查站点请求上限范围 1–100、单轮反馈证据范围 10–100、Top-M 范围 10–150。不要为了验收修改后忘记恢复。"
step "关闭最终列表重排开关，确认 Top-M 禁用且原值保留；再恢复原开关状态。"
step "检查“允许模型提前收窄搜索范围”及其说明仍存在。未经必要不要保存设置；如有修改，保存后恢复原值。"
step "展开“隐私与发送给模型的数据”，确认说明包含原生元数据、作者本地显示、正文派生标题、正文/回帖/登录信息不发送，以及 API key 存储边界。"
step "回搜索页确认检索详情与搜索页隐私说明默认折叠，点击可展开且键盘可操作。"
require_yes "设置控件、隐私说明和折叠交互均符合预期？"

stage "检查真实搜索状态与结果"
say "此阶段会向当前站点发起检索，并按配置调用模型。请使用普通、非敏感查询；不要把任何凭据粘贴到向导。"
step "记下当前站点请求上限；如需控制请求量，可暂时设为 3–5 并保存，验收后恢复原值。"
step "提交一个普通校园论坛查询，确认状态行更新，检索详情可查看波次/请求/检索词，结果可渐进出现。"
step "运行中点击“停止并查看结果”，确认停止后保留已有结果；若进入最终重排，确认按钮变为“取消最终列表重排”，且可单独取消。"
step "再次提交另一个查询，确认新搜索替换旧运行；关闭再打开面板，确认关闭面板不会终止搜索。"
step "结果应为紧凑列表行，标题链接仍在新标签页打开；普通结果不显示模型等级、分数、排序原因或内部检索历史。"
step "如有隐藏结果，确认它们默认折叠，展开后仍是普通结果行；如遇提前终止，应明确标识为部分结果。"
step "恢复原站点请求上限、重排开关及其他本次更改的设置，并确认保存成功。"
note "真实站点未出现的异常、软隔离或重排取消分支，不要通过高频重试强行触发；这些边界由自动测试覆盖。"
require_yes "真实搜索交互、结果展示符合预期，并已恢复设置？"
