#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
FRONTEND_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
REPO_DIR=$(cd "$FRONTEND_DIR/.." && pwd)

require_yes() {
  if ! confirm "$1"; then
    warn "本阶段未通过。验收在这里停止，不记录为通过。"
    exit 1
  fi
}

banner "Issue #30 查询组合、可验证扩展与模型元数据边界验收"

say "本向导不读取浏览器存储，也不保存 API key、Cookie、登录态、帖子内容、请求内容或模型响应。"
say "协议归一化、请求顺序、扩展授权、局部失败隔离、排序稳定性与失败回退由自动测试验收；人工阶段只检查页面和本地请求中能稳定观察的边界。"
warn "不要复制、截图或展示 DevTools 中的 Authorization、Cookie、请求正文、帖子内容或模型响应。"
pause "确认可以运行本地检查，并使用本人已登录的 CC98 会话后按 Enter。"

stage "运行自动验收证据"
say "即将运行完整前端测试、类型检查、生产构建和扩展产物检查。"
(cd "$FRONTEND_DIR" && npm test && npm run typecheck && npm run build)
grep -F '查询组合不完整，仍将执行现有检索词。' "$FRONTEND_DIR/src/extension/search-session.ts" >/dev/null
grep -F '作者只在本地结果卡片显示，不会发送给模型。' "$FRONTEND_DIR/src/extension/content.tsx" >/dev/null
say "自动检查已验证以下行为："
step "首轮角色 precise、balanced、anchor 的归一化；标题来源的 anchor 组合、预算优先级和组合不完整降级。"
step "query 与 evidence 扩展的协议、support_keys 授权、标题来源限制、逐项隔离及 stop_suggestions 的已执行零命中限制。"
step "作者不进入反馈或最终重排序模型负载；仅作者变化不增加模型可见的独立证据版本，且本地卡片仍保留作者。"
step "板块和回复数的提示词边界、回复数不参与本地预排序，以及模型超时、网络失败和无效响应的本地回退。"
step "现有搜索运行、模型协议和 wire payload 接缝覆盖上述行为，未新增测试专用生产接口。"
require_yes "完整测试、类型检查、构建、产物检查和文档断言均已通过？"

stage "重载扩展并保留现有设置"
say "在 Edge 打开 edge://extensions，启用开发人员模式，然后重载已加载的扩展。"
say "如果尚未加载，请点击“加载解压缩的扩展”，选择下面的目录："
say "$FRONTEND_DIR/dist"
open_url "https://www.cc98.org/"
step "刷新 CC98 页面，点击右下角“搜”悬浮球。"
step "确认 CC98 已登录、模型设置可用。不要改动、复制或显示 API key。"
step "如需调整请求次数上限以完成本次人工搜索，只在本地记下原值；第五阶段会恢复它。"
require_yes "扩展已重载，CC98 和模型均可用，并已记下任何将临时修改的设置？"

stage "检查本地展示与隐私文案"
say "此阶段会发送一次真实 CC98 和模型请求。请选择无敏感内容的普通检索，不要为制造边界状态反复提交。"
step "提交一个通常会返回多条结果的查询，等待至少一条结果出现。"
step "确认每张结果卡片仍显示作者（有作者数据时）、板块、时间和回复数。"
step "展开或查看隐私说明，确认其明确表示作者只在本地结果卡片显示，不会发送给模型。"
step "确认界面中没有 learned_terms 字段、标签或相关状态。"
note "“查询组合不完整”只在模型计划恰好缺少 anchor 或非 anchor 时出现；不要为了触发它重复请求。该分支由第一阶段自动验收。"
require_yes "作者仍在本地展示，隐私文案正确，且未出现 learned_terms？"

stage "本地核对模型载荷的作者边界"
say "只在自己的浏览器中检查一次请求。不要打开或复制请求头，不要记录 Authorization、Cookie、请求正文、帖子内容或模型响应。"
step "打开 DevTools 的 Network 面板，筛选本次搜索产生的 chat/completions 请求。"
step "仅在 Payload 的字段名层面确认反馈和最终重排请求没有 author 字段；不要读取或复制字段值。"
step "如果本次没有触发最终重排，请不要重复搜索制造请求；以第一阶段的 final rerank wire-payload 测试为验收证据。"
step "关闭 DevTools，避免保留或分享网络记录。"
require_yes "已在本地确认可观察到的模型请求不含 author，且没有查看、复制或记录任何敏感数据？"

stage "恢复设置并完成记录"
step "如第二阶段临时修改过站点请求次数上限或其他模型设置，现在恢复原值并保存。"
step "确认正常搜索仍可完成；无论模型超时、网络失败、无效 JSON 或无效顶层结构，已有候选均由第一阶段的自动测试验证会保留并回退本地逻辑。"
step "将本次验收结论仅记录为通过或未通过；不要附带 API key、Cookie、认证头、请求正文、模型响应或帖子内容。"
require_yes "临时设置已恢复，并已按自动与人工证据完成 Issue #30 验收？"

finish
