#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
FRONTEND_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
REPO_DIR=$(cd "$FRONTEND_DIR/.." && pwd)

require_yes() {
  if ! confirm "$1"; then
    warn "本阶段未通过。验收在这里停止，不记录为通过。"
    exit 1
  fi
}

banner "Issue #28 停止、重排取消与运行替换验收"

say "本向导不读取浏览器存储，也不保存 API key、Cookie、登录态、请求内容或模型响应。"
say "取消竞态、迟到响应、失败回退、停止优先级和公开快照由自动测试验收；人工阶段只检查页面上能稳定观察的行为。"
warn "不要复制、截图或展示 DevTools 中的 Authorization、Cookie、帖子内容和模型请求。"
pause "确认可以运行本地检查，并使用本人已登录的 CC98 会话后按 Enter。"

stage "运行自动验收证据"
say "即将运行完整前端测试、类型检查、生产构建和扩展产物检查。"
(cd "$FRONTEND_DIR" && npm test && npm run typecheck && npm run build)
grep -F '“停止并查看结果”只终止当前和后续站点请求' "$REPO_DIR/README.md" >/dev/null
grep -F '再次提交查询会替换整个旧运行' "$REPO_DIR/README.md" >/dev/null
say "自动检查已验证以下行为："
step "用户停止后不等待请求间隔或未响应请求，已取得的至少两条主结果仍进入独立的 Final Rerank。"
step "取消重排不接受迟到顺序或部分删除，候选、本地预排序和原停止原因保持不变。"
step "检索、反馈和重排期间的运行替换都会取消旧运行，迟到成功、失败或取消响应不能再发布快照。"
step "反馈失败保留非软隔离候选并跳过重排；重排失败只回退本地预排序，不覆盖原停止原因。"
step "停止优先级、完整波次反馈、公开快照阶段、planner 调用和站点请求顺序均有确定性测试。"
step "README 已分别说明停止检索、取消重排、本地回退和新查询替换旧运行。"
require_yes "完整测试、类型检查、构建、产物检查和文档断言均已通过？"

stage "重载扩展并准备验收"
say "在 Edge 打开 edge://extensions，启用开发人员模式，然后重载已加载的扩展。"
say "如果尚未加载，请点击“加载解压缩的扩展”，选择下面的目录："
say "$FRONTEND_DIR/dist"
open_url "https://www.cc98.org/"
step "刷新 CC98 页面，点击右下角“搜”悬浮球，再打开模型设置。"
step "确认 CC98 已登录、模型配置可用。不要改动、复制或显示 API key。"
step "记下当前的站点检索请求次数上限、最终列表重排开关和 Top-M，第六阶段需要恢复。"
step "开启最终列表重排，将请求次数上限设为至少 10，Top-M 保持 30 或原有合法值，然后保存。"
require_yes "扩展已重载，CC98 和模型均可用，并已记下原设置？"

stage "停止站点检索并进入重排"
say "此阶段会发送真实 CC98 和模型请求。只执行一次普通查询，不要为制造竞态连续重试。"
step "提交一个通常会返回多个候选的查询，例如“找操作系统课程资料和经验帖”。"
step "等主结果至少出现两条，且状态仍是站点检索或反馈时，点击“停止并查看结果”。"
step "确认不再开始新的检索波次，进度区不再把已取消的检索词显示为“正在执行”。"
step "确认页面进入“正在重排本地预排序前 N 条结果”，操作按钮改为“取消最终列表重排”。"
note "如果候选不足两条或重排返回太快，不要高频重试。独立取消范围和立即停止由第一阶段的测试验收。"
require_yes "停止检索后没有新波次，已有至少两条候选进入了一次 Final Rerank？"

stage "取消 Final Rerank 并核对本地回退"
step "再执行一次能产生至少两条主结果的查询。在重排前记下主结果数量和前三条标题的顺序。"
step "在站点检索或反馈阶段点击“停止并查看结果”，等“取消最终列表重排”出现后立即点击。"
step "确认状态同时说明“已由用户停止”和“已取消最终列表重排，保留本地预排序”，而不是显示重排成功。"
step "核对主结果数量和前三条顺序与取消前一致，没有候选被删除，也没有局部重排顺序落地。"
note "重排响应可能快于人工操作。若未能点到取消，以第一阶段的迟到成功响应测试为验收证据，不要重复消耗模型调用。"
require_yes "取消操作、本地顺序、候选数量和 user stopped 原因均符合预期？"

stage "在检索或反馈期间替换旧运行"
step "提交一个会持续多个波次的查询 A。当状态显示正在检索或“正在判断第 N 个检索波次的候选证据”时，把输入框改成不同主题的查询 B。"
step "点击“开始新搜索”。确认查询 B 从规划阶段重新开始，不继承查询 A 的结果、检索词、请求计数或停止原因。"
step "继续观察直到查询 B 完成。确认界面没有突然恢复查询 A 的结果、阶段、状态文案或停止原因。"
note "反馈阶段可能很短。若无法稳定命中，以第一阶段的反馈迟到响应隔离测试为准，不要高频重试。"
require_yes "查询 B 完全替换了检索或反馈中的查询 A，且旧运行未再更新界面？"

stage "在重排期间替换运行并恢复设置"
step "再提交查询 A，让它自然结束检索，或在至少有两条主结果后点击“停止并查看结果”。"
step "在“取消最终列表重排”显示期间，把输入框改成查询 B，点击“开始新搜索”。"
step "确认查询 B 进入规划或检索阶段，查询 A 的重排成功、失败或取消响应都没有改动查询 B 的列表和状态。"
step "打开模型设置，恢复第二阶段记下的站点请求次数上限、最终列表重排开关和 Top-M，然后保存。"
step "确认本向导没有要求输入、保存或上传 API key、Cookie、登录态、请求内容或模型响应。"
note "重排可能在点击新搜索前完成。若未能命中竞态，以第一阶段的重排期间替换和迟到响应测试为验收证据。"
require_yes "重排期间的替换没有污染新运行，且所有临时设置已恢复？"

finish
