#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
FRONTEND_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

require_yes() {
  if ! confirm "$1"; then
    warn "本阶段未通过。验收在这里停止，不记录为通过。"
    exit 1
  fi
}

banner "Issue #25 浏览器验收"

say "请求顺序、独立证据、等级归并、选择上限、失败回退和隐私字段由自动测试验收。"
say "本向导只检查浏览器中能观察的行为，不读取浏览器存储，也不保存 API key、登录态、请求内容或模型响应。"
warn "DevTools 中会显示本人的站点请求和模型请求。只在本机查看 Payload，不复制、不截图，也不要打开或展示 Authorization 与 Cookie。"
pause "确认使用本人的已登录站点会话和已配置模型后按 Enter。"

stage "重载扩展并准备验收"
say "在 Edge 打开 edge://extensions，启用开发人员模式，然后重载已加载的扩展。"
say "如果尚未加载，请点击“加载解压缩的扩展”，选择下面的目录："
say "$FRONTEND_DIR/dist"
open_url "https://www.cc98.org/"
step "刷新 CC98 页面，点击右下角“搜”悬浮球。"
step "打开模型设置，确认模型配置仍可用。不要改动、复制或显示 API key。"
step "记住当前的站点请求次数上限、单次反馈证据数量和最终模型阶段开关，最后一个阶段需要恢复它们。"
require_yes "扩展已重载，CC98 已登录，模型设置可用于验收？"

stage "检查反馈证据数量设置"
step "确认“单次反馈证据数量”存在。旧设置没有该字段时应显示默认值 30。"
step "把值改为 9 并尝试保存。表单应阻止越过下限；把值改为 101 时也应阻止保存。"
step "分别保存 10 和 100，关闭面板再打开，确认合法值可以保存。"
step "本阶段结束前先设为 30。最后一个阶段再恢复你的原值。"
note "非法值回退、取整和 10 至 100 夹取由 settings.test.ts 覆盖；这里核对浏览器控件和保存行为。"
require_yes "默认值、输入边界和保存状态都符合预期？"

stage "核对首个检索波次"
say "此阶段会发送真实 CC98 请求和模型请求。使用普通课程资料查询，不要连续重复运行。"
step "把站点请求次数上限设为至少 10 并保存。打开 DevTools → Network，开启 Preserve log，然后清空现有记录。"
step "提交一个通常会规划多个检索词的查询，例如“找近两年的操作系统课程讨论和资料”。"
step "在面板展开检索进度，记下首轮检索词。Network 中用 topic/search 找到站点搜索，用 chat/completions 找到模型调用。"
step "只在本机查看请求 Payload。确认每个已执行的首轮检索词先各有一个第一页请求；第一次反馈调用出现在任何首轮词的续页请求之前。"
step "确认同一波次中，同一个检索词没有出现两次站点请求。若请求上限先耗尽，只核对已经执行的请求。"
note "不要复制 Payload。来源位次、游标保护和波次内单词单请求由自动测试精确覆盖。"
require_yes "首轮各词先取一页，第一次反馈早于首轮词续页？"

stage "核对后续波次和请求边界"
step "继续观察同一次搜索。若反馈产生新检索词，确认该词的第一次站点请求早于旧检索词的下一次续页。"
step "若同时存在新词和旧词续页，确认旧词仍会在后续波次继续请求，没有一直停在同一页。"
step "对照 Network 时间，确认 CC98 站点请求仍保留约 2 秒间隔；模型调用不增加面板中的站点请求次数。"
step "把站点请求次数上限临时设为 1，再执行一次能命中候选的查询。确认只发生 1 次站点请求，已完成波次仍可进入反馈，最后以请求上限原因保留已有结果。"
note "如果本次模型没有生成新检索词或没有产生分页，以 issue-25.test.ts 的确定性顺序测试为验收证据，不要为了触发分支高频重试。"
require_yes "可观察的后续顺序、请求间隔和共享请求上限符合预期？"

stage "检查软隔离和反馈负载"
step "把请求次数上限恢复到足够完成普通搜索的值，执行一个结果较宽的查询。"
step "如果页面出现“已隐藏的明确无关结果”，确认它默认折叠；展开后仍使用普通结果卡片和原帖链接。反复展开、折叠不应把条目移回主列表。"
step "在 Network 中选择反馈用 chat/completions 请求，只查看 Payload。候选应使用 c0、c1 一类临时键，并且每项最多有 3 个不同 matched_queries。"
step "确认反馈 Payload 没有 URL、平台或来源标识、来源位次、波次、片段、正文、回帖、认证数据或用户身份字段。"
note "grade 0 重判恢复、未知键、非法等级、重复键、每词最多 4 条、4000 UTF-8 字节上限和模型失败回退由自动测试覆盖。"
require_yes "软隔离行为和本机可见的反馈负载边界符合预期？"

stage "朵朵冒烟并恢复设置"
open_url "https://www.duoduo.link/"
step "确认朵朵处于本人已登录状态，刷新页面并打开搜索面板。"
step "执行一个普通查询，确认搜索可以完成，结果卡片可以打开原帖，站点请求格式和分页行为没有异常。"
step "在 Network 中找到带 candidates 的反馈模型请求，只查看 Payload。朵朵正文派生显示标题对应的 title 应为空；不要复制请求。"
step "回到模型设置，恢复第一个阶段记下的请求次数上限、反馈证据数量和最终模型阶段开关。"
step "确认本向导没有要求输入、保存或上传 API key、Cookie、登录态、帖子正文或模型响应。"
note "如果朵朵当前没有可用候选，以 Duo adapter 和 integration 自动测试为协议验收证据，不要为验收主动触发验证码或限流。"
require_yes "朵朵冒烟通过，正文派生标题未外发，所有设置已经恢复？"

finish
