#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
FRONTEND_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

require_yes() {
  if ! confirm "$1"; then
    warn "本阶段未通过。验收在这里停止，不记录为通过。"
    exit 1
  fi
}

banner "Issue #27 最终列表重排验收"

say "本向导不读取浏览器存储，也不保存 API key、Cookie、登录态、请求负载或模型响应。"
say "白名单、删除资格、键规范化和失败回退由自动测试验收；人工阶段只检查页面上能可靠观察的行为。"
pause "确认可以运行本地检查，并使用本人的已登录 CC98 会话后按 Enter。"

stage "运行自动验收证据"
say "即将运行完整前端测试、类型检查、生产构建和扩展产物检查。"
(cd "$FRONTEND_DIR" && npm test && npm run typecheck && npm run build)
say "自动检查覆盖以下不应通过人工查看模型请求来验收的标准："
step "旧设置迁移、默认值、Top-M 10 至 150 的规范化，以及关闭开关不影响反馈轮。"
step "单次 Top-M 调用、少于 M 时不填充、零条或一条时跳过，以及 Top-M 外顺序。"
step "相关性等级 0 和时间范围外候选不进入负载；朵朵正文派生标题为空；两次白名单投影。"
step "跨相关性等级排序；只删除请求前未判断候选；重复、未知和遗漏临时键的保守处理。"
step "超时、网络失败、非法 JSON、不可识别结构、用户取消和新查询替换时的本地回退。"
step "后台消息校验、20 秒模型超时、1200 tokens 输出限制，以及 API key 不返回 content script。"
if ! command -v rg >/dev/null 2>&1; then
  warn "缺少 rg，无法执行旧协议静态检查。"
  exit 1
fi
if rg -n "planner:screen|screenResults|SCREENING_BATCH|phase: 'screening'" "$FRONTEND_DIR/src"; then
  warn "仍发现旧的多批次筛选生产协议。"
  exit 1
fi
if [[ -e "$SCRIPT_DIR/issue-22-acceptance-wizard.sh" || -e "$SCRIPT_DIR/issue-23-acceptance-wizard.sh" ]]; then
  warn "仍存在要求旧多批次筛选行为的可执行验收向导。"
  exit 1
fi
require_yes "完整测试、类型检查、构建、产物检查和旧协议静态检查均已通过？"

stage "重载扩展并检查设置控件"
say "在 Edge 打开 edge://extensions，启用开发人员模式，然后重载已加载的扩展。"
say "如果尚未加载，请点击“加载解压缩的扩展”，选择下面的目录："
say "$FRONTEND_DIR/dist"
open_url "https://www.cc98.org/"
step "刷新 CC98 页面，点击右下角“搜”悬浮球，再打开模型设置。"
step "确认模型配置可用。不要改动、复制或展示 API key。"
step "记住当前的站点请求次数上限、最终列表重排开关和 Top-M，最后一个阶段需要恢复。"
step "确认 Top-M 输入声明的范围为 10 至 150。新安装默认开启和默认值 30 已由第一阶段测试固定。"
step "关闭最终列表重排，确认 Top-M 输入立即禁用，显示值不变；重新开启后确认原值仍在。"
step "把 Top-M 设为 10 并保存。重新打开模型设置，确认值仍为 10。"
require_yes "开关、Top-M 禁用状态和保存行为符合预期，并已记下原设置？"

stage "关闭重排并检查反馈轮独立运行"
step "关闭最终列表重排，把站点检索请求次数上限设为足以产生多个波次的值，例如 10，然后保存。"
step "提交一个通常能产生多个检索波次和多个结果的查询，例如“找近两年的操作系统课程资料和讨论”。"
step "观察搜索过程。出现时确认“正在判断第 N 个检索波次的候选证据”状态仍会运行。"
step "等待搜索结束，确认已有结果保留，最终状态没有“正在重排”“重排完成”或“重排未完成”。"
note "反馈状态可能一闪而过。关闭最终重排不关闭反馈轮的确定性证据以第一阶段测试为准，不要为捕捉状态高频重试。"
require_yes "关闭最终列表重排后搜索和反馈轮仍正常，且没有进入最终列表重排？"

stage "开启并检查单次 Top-M 重排"
step "重新开启最终列表重排，保持 Top-M 为 10，然后保存。"
step "提交一个容易产生至少两条主结果候选的宽查询。候选不足两条时换一个自然的宽查询，不要连续高频请求。"
step "等待搜索结束，确认最终状态包含“最终列表重排完成”；结果列表仍可正常打开原帖。"
step "确认界面没有“共 N 批”“已完成 x/y 批候选筛选”或“最终意图筛选”等旧文案。"
step "如果某次查询只有零条或一条主结果候选，确认它直接结束，不显示最终列表重排状态。"
note "单次调用、实际候选数量、Top-M 外顺序和删除保护不暴露在页面上，由第一阶段测试验收。"
require_yes "正常完成路径使用新的最终列表重排状态，且没有旧多批次筛选语义？"

stage "检查取消回退、卡片隐私并恢复设置"
step "发起一个宽查询。在已有至少两条结果时点击“停止并查看结果”，观察是否进入最终列表重排。"
step "如果出现“取消最终列表重排”按钮，点击一次，确认状态说明已取消并保留本地预排序，已有结果没有被清空。"
note "模型响应可能快于人工点击。若按钮未出现，不要反复请求；取消竞态和失败回退由第一阶段测试验收。"
step "检查普通结果卡片只显示名次、标题、板块、发布时间、回复数和原帖入口。"
step "确认卡片不显示相关性等级、临时键、检索支持、来源位次、轮次、URL 之外的内部数据或模型删除建议。"
step "恢复第二阶段记下的站点请求次数上限、最终列表重排开关和 Top-M，并保存。"
require_yes "回退与卡片隐私符合预期，并已恢复原设置？"

finish
