#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
FRONTEND_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

run_tests() {
  (cd "$FRONTEND_DIR" && npm test -- "$@")
}

require_yes() {
  if ! confirm "$1"; then
    warn "本阶段尚未通过。请记录非敏感的失败步骤，修复后重新运行向导。"
    exit 1
  fi
}

assert_present() {
  local pattern="$1"
  shift
  if ! grep -nF -- "$pattern" "$@" >/dev/null; then
    warn "缺少预期实现或文档：$pattern"
    exit 1
  fi
}

banner "Issue #34 检索事实、Search Ledger 与 clue-only 验收"

say "本向导不会读取、保存或输出 API key、Cookie、Authorization、登录态、帖子内容或模型响应。"
say "字段白名单、统计口径、4000 字节上限和扩展准入由确定性测试验收；真实站点阶段只做一次普通搜索。"
warn "不要复制、截图或分享 DevTools 中的请求头、字段值、帖子内容或模型响应。人工阶段只核对字段名。"
pause "确认可以运行本地检查，并使用本人已登录的 CC98 会话后按 Enter。"

stage "完整自动回归与扩展产物"
say "运行完整前端测试、TypeScript 检查、生产构建和扩展产物校验。"
(cd "$FRONTEND_DIR" && npm test && npm run typecheck && npm run build)
say "已验证完整测试、类型检查、Vite 构建和 verify:dist。"
require_yes "完整自动回归是否全部通过？"

stage "Final Rerank 检索事实与隐私"
say "以下测试只使用本地对象、mock 模型和 mock 搜索源，不访问真实站点或模型端点。"
run_tests --reporter=verbose \
  src/extension/issue-34.test.ts \
  src/extension/final-reranking.test.ts \
  src/extension/planner.test.ts \
  src/extension/background.test.ts
say "已验证："
step "matched_queries 最多保留 5 个不同检索词，并按首次观察顺序排列。"
step "independent_query_count 使用完整观察集合，不受 5 个展示词限制。"
step "best_source_position 取全部合法正位次的最小值；没有已知位次时为 null。"
step "Final Rerank 不发送相关性等级、作者、URL、平台标识、正文、回帖、片段、轮次或认证数据。"
step "等级 1、2、3 仍只能排序，只有请求前未判断的候选可以接受删除建议。"
require_yes "Final Rerank 检索事实、字段白名单和删除保护是否通过？"

stage "Search Ledger 与 4000 字节装载"
run_tests --reporter=verbose \
  src/extension/issue-34.test.ts \
  src/extension/issue-25.test.ts \
  src/extension/search-session.test.ts \
  src/extension/planner.test.ts
say "已验证："
step "Feedback 接收 remaining_requests，以及每个已执行检索分支的 Search Ledger。"
step "pages、hits、unique_candidates、new_on_last_page 使用各自定义的页数、原始命中、分支去重和全局新增口径。"
step "grade_2_3 与 grade_0 使用分支候选的当前最新等级；同一候选可以计入多个检索分支。"
step "can_continue 与该分支当前是否存在 continuation 一致。"
step "完整 JSON 不超过 4000 UTF-8 字节，先保留查询、日期、剩余请求、Ledger 和已执行检索信息。"
step "候选只使用剩余空间；过长条目会被跳过，后面的较短条目仍可装入。"
step "Feedback 候选的 matched_queries 上限仍为 3。"
require_yes "Search Ledger 统计和负载装载优先级是否通过？"

stage "clue-only 矩阵与既有调度保护"
run_tests --reporter=verbose \
  src/extension/issue-34.test.ts \
  src/extension/issue-30.test.ts \
  src/extension/issue-31.test.ts \
  src/extension/search-session.test.ts
assert_present "clue_only" "$FRONTEND_DIR/src/extension/planner.ts"
assert_present "老师突然说这学期换书了" "$FRONTEND_DIR/src/extension/issue-34.test.ts"
say "已验证："
step "全部支持为等级 2/3，或等级 1 与至少一个等级 2/3 混合时，按普通 evidence expansion 接受。"
step "全部支持为等级 1 时，只有 clue_only: true 才能通过。"
step "等级 0、未知键、本次 Feedback 负载外的键和没有模型可见原生标题的候选不能提供支持。"
step "标题“老师突然说这学期换书了”可以为查询“教材更换”提供 grade 1 clue-only provenance。"
step "本地不做标题子串、token overlap 或语义相似度校验。"
step "查询规范化、去重、首见检查、请求上限、一次救援、请求间隔和取消行为继续生效。"
require_yes "clue-only 准入矩阵和既有调度保护是否通过？"

stage "Edge 单次真实请求检查"
open_url "edge://extensions"
step "启用开发人员模式并重载本扩展；如尚未加载，选择目录：$FRONTEND_DIR/dist"
open_url "https://www.cc98.org/"
step "确认已登录 CC98，刷新页面并打开右下角“搜”悬浮球。"
step "确认现有模型设置可用。不要复制、显示或修改 API key。"
step "打开 DevTools 的 Network 面板，筛选 chat/completions，然后提交一条不含个人信息、通常能返回多条结果的普通查询。"
step "仅检查 Feedback 用户消息的字段名：应包含 remaining_requests、search_ledger、executed_searches 和 candidates。"
step "仅检查一条 Ledger 记录的字段名：pages、hits、unique_candidates、new_on_last_page、grade_2_3、grade_0、can_continue。"
step "如本次触发 Final Rerank，仅检查候选字段名包含 matched_queries、independent_query_count、best_source_position，且不含 grade、author、url、source_id、body、replies、snippet、round 或认证字段。"
step "不要为了触发 clue_only、分页或 Final Rerank 重复请求。未稳定触发的分支以前四阶段的自动测试为验收证据。"
step "关闭 DevTools，避免保留或分享网络记录。"
require_yes "真实请求中可观察到的字段名和隐私边界是否符合预期？"

stage "恢复设置与验收记录"
say "不要在验收记录中附加 API key、Cookie、Authorization、请求正文、字段值、模型响应或帖子内容。"
step "如果人工阶段临时修改过站点请求次数上限或其他设置，现在恢复原值并保存。"
step "确认自动阶段全部通过，真实会话没有出现隐藏请求、超额请求、结果丢失或敏感字段出域。"
step "只记录 Issue #34 通过或未通过，以及非敏感的失败步骤名称。"
require_yes "设置已恢复，并已完成 Issue #34 的自动与人工验收？"
say "Issue #34 验收完成。"

finish
