#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
FRONTEND_DIR="$PROJECT_ROOT/frontend"
MOCK_SERVER="$SCRIPT_DIR/issue-8-mock-openai-server.mjs"
MOCK_PORT="${MOCK_PORT:-18787}"
MOCK_LOG=$(mktemp "${TMPDIR:-/tmp}/issue-8-mock.XXXXXX.log")
MOCK_PID=""
TEST_KEY_MARKER="issue8-acceptance-${RANDOM}-$(date +%s)"
VALID_BASE_URL="http://127.0.0.1:${MOCK_PORT}/valid/v1"
INVALID_BASE_URL="http://127.0.0.1:${MOCK_PORT}/invalid/v1"

cleanup() {
  if [[ -n "$MOCK_PID" ]] && kill -0 "$MOCK_PID" >/dev/null 2>&1; then
    kill "$MOCK_PID" >/dev/null 2>&1 || true
    wait "$MOCK_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

start_mock() {
  MOCK_PORT="$MOCK_PORT" node "$MOCK_SERVER" >"$MOCK_LOG" 2>&1 &
  MOCK_PID=$!
  for _ in {1..20}; do
    if curl --silent --fail "http://127.0.0.1:${MOCK_PORT}/health" >/dev/null; then return 0; fi
    sleep 0.2
  done
  warn "本机 mock 未能监听端口 ${MOCK_PORT}。可用 MOCK_PORT=其他端口 重新运行。"
  return 1
}

assert_optional_permissions() {
  node -e '
    const manifest = JSON.parse(require("node:fs").readFileSync(process.argv[1], "utf8"));
    const required = ["https://*/*", "http://*/*"];
    if (!required.every((permission) => manifest.optional_host_permissions?.includes(permission))) process.exit(1);
  ' "$FRONTEND_DIR/dist/manifest.json"
}

banner "Issue #8 模型端点与隐私边界验收"

stage "构建、加载并打开 Edge 验收页"
say "本向导不会询问、读取、写入或显示真实 API key。不会创建 .env 或修改 GitHub。"
step "在本地构建当前扩展产物。"
(cd "$FRONTEND_DIR" && npm run build)
assert_optional_permissions
say "已确认 manifest 同时声明 http://*/* 与 https://*/* 为 optional host permissions。"
open_url "edge://extensions"
step "在 Edge 启用开发人员模式；找到本扩展，点击“重新加载”。"
step "打开本扩展“详细信息”，在 service worker 旁点击“检查”。在该 DevTools Console 勾选 Preserve log 后清空 Console；后续不要在其中输入或展示真实 key。"
open_url "https://www.cc98.org/"
step "确认自己已登录 CC98，然后刷新该页面。请不要在本向导或浏览器控制台输入真实 API key。"
pause "完成扩展重载、CC98 刷新，并准备好查看扩展 service worker 的 Console 后按 Enter"

stage "有效首轮规划与按需权限"
start_mock
say "本机 mock 已启动。它只记录请求方法和路径，不读取 Authorization 或请求正文。"
say "请在 CC98 右下角 98 → 模型设置中填写以下非敏感验收值："
step "base URL：$VALID_BASE_URL"
step "API key：$TEST_KEY_MARKER（这只是一次性测试标记，不是真实密钥）"
step "模型名称：issue-8-acceptance"
step "点击“保存设置”。首次保存应由 Edge 请求访问 127.0.0.1:${MOCK_PORT}；在权限弹窗中允许。"
step "回到“搜索”，输入“验收首轮规划”并点击“开始搜索”。看到状态离开“正在规划首轮检索词…”后，立即点击“停止并查看结果”。"
pause "完成有效规划操作后按 Enter"
if rg --quiet --fixed-strings "POST /valid/v1/chat/completions" "$MOCK_LOG"; then
  say "✓ mock 已收到至少一次有效首轮 /chat/completions 请求。"
else
  warn "未观察到有效首轮请求。请确认 CC98 已登录、扩展已刷新、权限已允许，然后重试本阶段。"
  exit 1
fi

stage "非法模型结构的中文错误"
say "将模型设置的 base URL 改为：$INVALID_BASE_URL"
step "保留测试标记和模型名称，保存设置；同一 host 已授权时通常不会再次弹窗。"
step "回到“搜索”，输入“验收非法结构”，点击“开始搜索”。"
step "预期面板中文状态：模型返回的查询计划结构无效。"
pause "确认看到了该中文错误后按 Enter"
if rg --quiet --fixed-strings "POST /invalid/v1/chat/completions" "$MOCK_LOG"; then
  say "✓ mock 已收到非法结构验收请求。"
else
  warn "未观察到非法结构请求；本阶段尚未通过。"
  exit 1
fi

stage "API key、DOM、日志与仓库边界"
step "刷新 CC98 页面，重新打开模型设置。API key 输入框应为空，并显示“已保存；留空表示不修改”。"
step "在 CC98 页面 DevTools Console 执行：document.querySelector(\"input[type=password]\") === null"
step "预期为 true：保存的 key 没有进入 CC98 页面的 light DOM。"
step "在 edge://extensions → 本扩展“详细信息”中打开 service worker 的检查窗口；确认 Console 没有输出本次测试标记。不要展开或截图 Network 的 Authorization 请求头。"
step "仓库扫描只查找本次临时标记，不会读取扩展存储。"
if rg --fixed-strings --hidden --glob '!node_modules' --glob '!dist' --glob '!.git' "$TEST_KEY_MARKER" "$PROJECT_ROOT"; then
  warn "临时标记出现在仓库文件中；请停止验收并检查上述匹配。"
  exit 1
else
  say "✓ 临时测试标记未出现在仓库文件中。"
fi
say "额外自动回归：后台测试会断言 key 不回传给 content script，且仅请求配置的模型主机。"
(cd "$FRONTEND_DIR" && npm test -- src/extension/background.test.ts)
say "✓ API key 回传与模型主机权限单元测试通过。"

finish
