#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
FRONTEND_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

run_tests() {
  (cd "$FRONTEND_DIR" && npm test -- "$@")
}

require_yes() {
  if ! confirm "$1"; then
    warn "本阶段尚未通过。请记录现象，修复后重新运行向导。"
    exit 1
  fi
}

assert_absent() {
  local pattern="$1"
  shift
  if grep -nF -- "$pattern" "$@"; then
    warn "发现已要求删除的生产接口：$pattern"
    exit 1
  fi
}

banner "Issue #31 无正信号救援与 CC98 分页排空验收"

say "本向导不会读取或写入 API key、Cookie、CC98 token、Authorization、浏览器存储或帖子内容。"
say "精确边界由 mock 测试验收；真实站点阶段只做一次普通搜索，不人为制造限流、空页或大量请求。"
pause "确认可以运行本地检查，并使用本人已登录的 CC98 会话后按 Enter。"

stage "完整自动回归与扩展产物"
say "运行完整前端测试、TypeScript 检查、生产构建和扩展产物校验。"
(cd "$FRONTEND_DIR" && npm test && npm run typecheck && npm run build)
say "✓ 完整测试、类型检查、Vite 构建和 verify:dist 均已通过。"
require_yes "完整自动回归是否全部通过？"

stage "反馈信号与统一救援"
say "以下测试只使用 mock 模型和 mock 搜索源，不访问真实 CC98 或模型端点。"
run_tests --reporter=verbose \
  src/extension/issue-31.test.ts \
  src/extension/issue-30.test.ts \
  src/extension/planner.test.ts \
  src/extension/background.test.ts \
  src/extension/content.test.tsx
assert_absent "planBlindExpansion" \
  "$FRONTEND_DIR/src/extension/planner.ts" \
  "$FRONTEND_DIR/src/extension/search-session.ts" \
  "$FRONTEND_DIR/src/extension/content.tsx"
assert_absent "planner:blind" \
  "$FRONTEND_DIR/src/extension/background.ts" \
  "$FRONTEND_DIR/src/extension/content.tsx" \
  "$FRONTEND_DIR/src/extension/types.ts"
say "已验证："
step "信号从全部时间范围内候选派生 none、weak、positive；旧批次正信号仍有效，重判后可回到 weak。"
step "空候选和 grade 0/1 弱信号统一进入 Feedback，并且只有合法、首见、无 support_keys 的 query 搜索入队才消耗救援。"
step "重复、空白、非法或已执行 query 不消耗救援；同一失败输入没有新证据时不重复调用模型；每次运行最多一次救援。"
step "独立盲扩展方法、消息类型和运行分支已从生产代码删除。"
require_yes "反馈信号、统一救援和盲扩展删除证据是否通过？"

stage "请求预留与停止门"
say "继续使用确定性 mock 轨迹验证请求调度和停止语义。"
run_tests --reporter=verbose \
  src/extension/issue-31.test.ts \
  src/extension/issue-25.test.ts \
  src/extension/search-session.test.ts
say "已验证："
step "请求上限至少为 3 时先执行 anchor 和非 anchor，并为无正信号救援预留一次请求；positive 或救援不再需要时释放预留。"
step "上限为 1 或 2 时没有隐藏请求或超额请求，所有首页和分页共享同一个请求计数。"
step "合法新检索词先规范化、校验和入队，再判断 should_stop；救援仍有资格、首页待执行或刚入队首见词时拒绝停止建议。"
step "停止建议一旦接受，只永久关闭后续扩展；已入队首页和 continuation 继续，后续新证据仍进入 Feedback 并更新 grade 和软隔离。"
step "只有扩展关闭且已知分页排空才报告 model_stop；分页未耗尽而撞上上限时报告 request_limit 和部分结果。"
require_yes "请求预留、停止门和关闭后反馈轨迹是否通过？"

stage "CC98 分页与既有保护"
say "此阶段验证 adapter 的原始响应分页，以及搜索 core 的既有停止保护。"
run_tests --reporter=verbose \
  src/extension/sites/cc98/index.test.ts \
  src/extension/search-session.test.ts \
  src/extension/issue-25.test.ts \
  src/extension/sites/duo/integration.test.ts \
  src/extension/ranking.test.ts \
  src/extension/final-reranking.test.ts
say "已验证："
step "CC98 始终发送 size=20；满 20 条和非空短页都产生下一 offset，空页终止分页。"
step "offset 按原始响应长度推进，单条解析失败不会造成重叠或跳位。"
step "多个 continuation 保持广度优先，新接受的检索词优先取得首页。"
step "游标循环保护、请求间隔、时间提前停止、模型失败保留候选和共享请求上限保持有效。"
step "grade 1 与未判断候选保留；grade 0 软隔离和最终重排删除保护没有放宽。"
require_yes "CC98 分页和既有保护的自动证据是否通过？"

stage "Edge 真实会话烟雾验收"
open_url "edge://extensions"
step "启用开发人员模式并重载本扩展；如尚未加载，选择目录：$FRONTEND_DIR/dist"
open_url "https://www.cc98.org/"
step "确认已登录 CC98，刷新页面并打开右下角“搜”悬浮球。"
step "在模型设置中确认现有 base URL、模型名称和 API key 可用；不要复制、展示或修改 API key。"
step "记下当前站点请求次数上限。如需缩短烟雾验收，可临时设为 3，但不要用真实站点制造 30 次请求、限流或异常响应。"
step "提交一条不含个人信息、预期能命中普通主题帖的查询。展开检索进度，观察轮次、已执行检索词和请求次数。"
step "确认结果逐轮保留；若出现“模型已关闭后续扩展”，状态必须同时说明已完成已知分页。"
step "若达到请求上限，状态必须说明保留当前部分结果，不能表示模型认为结果已经足够。"
note "零候选、弱信号救援、短页、空页和关闭后的 Feedback 不要求在真实站点强行制造，以前四阶段的 mock 轨迹为准。"
require_yes "真实会话的进度、结果保留和终止文案是否符合预期？"

stage "恢复设置与验收记录"
say "不要在验收记录中附加 API key、Cookie、Authorization、CC98 token、请求正文、模型响应或帖子内容。"
step "如果上一阶段临时修改过站点请求次数上限，现在恢复原值并保存。"
step "确认自动阶段均通过，真实会话没有出现隐藏请求、超额请求、结果丢失或错误的完整结果文案。"
step "只记录 Issue #31 通过或未通过，以及非敏感的失败步骤名称。"
require_yes "设置已恢复，并已完成 Issue #31 的自动与人工验收？"
say "✓ Issue #31 验收完成。"

finish
