import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Result = { topic: { id: string; title: string; board?: string; published_at?: string; reply_count?: number; url: string }; replies: { id: string; content: string; floor?: number }[]; score: number; evidence?: string; reason: string };
type SearchResponse = { query: { original_query: string; terms: string[] }; results: Result[]; partial: boolean; stop_reason?: string; requests_made: number; llm_experiment: boolean; llm_fallback?: string };

const api = async (path: string, init?: RequestInit) => { const response = await fetch(path, { credentials: 'include', ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || '请求失败'); return body; };

function App() {
  const [token, setToken] = useState(''); const [authenticated, setAuthenticated] = useState(false); const [query, setQuery] = useState(''); const [search, setSearch] = useState<SearchResponse | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [multi, setMulti] = useState(false); const [llm, setLlm] = useState(false);
  useEffect(() => { api('/api/auth/status').then(() => setAuthenticated(true)).catch(() => setAuthenticated(false)); }, []);
  async function login(event: React.FormEvent) { event.preventDefault(); setError(''); try { await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ access_token: token }) }); setAuthenticated(true); setToken(''); } catch (e) { setError((e as Error).message); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); setLoading(true); try { setSearch(await api(`/api/search?query=${encodeURIComponent(query)}&multi_request=${multi}&llm_experiment=${llm}`, { method: 'POST' })); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  async function logout() { await api('/api/auth/logout', { method: 'POST' }); setAuthenticated(false); setSearch(null); }
  return <main><header><div><p className="eyebrow">ZJU FORUM SEARCH</p><h1>在 CC98 里找到真正相关的讨论</h1><p className="sub">本地查询时检索，结果保留原帖链接和回帖证据。</p></div><span className={authenticated ? 'pill ok' : 'pill'}>{authenticated ? '已连接 CC98' : '未登录'}</span></header>
    {!authenticated ? <section className="panel"><h2>连接你的 CC98 会话</h2><p>access token 只会送到本地后端并保存在进程内存，页面不会持久化。</p><form onSubmit={login}><input type="password" value={token} onChange={e => setToken(e.target.value)} placeholder="粘贴 access token" autoComplete="off" required /><button>登录</button></form></section> : <><section className="panel"><div className="row"><h2>搜索主题帖</h2><button className="secondary" onClick={logout}>退出</button></div><form onSubmit={submit}><textarea value={query} onChange={e => setQuery(e.target.value)} placeholder="例如：高等数学期末复习资料和往年考试重点" required /><div className="controls"><label><input type="checkbox" checked={multi} onChange={e => setMulti(e.target.checked)} /> 受控多请求实验</label><label><input type="checkbox" checked={llm} onChange={e => setLlm(e.target.checked)} /> 外部 LLM 重排实验</label><button disabled={loading}>{loading ? '检索中…' : '开始搜索'}</button></div></form></section>{search && <section className="results"><div className="result-meta">查询：{search.query.original_query} · 请求 {search.requests_made} 次 {search.partial && <strong>· 结果可能不完整：{search.stop_reason}</strong>}</div>{search.llm_fallback && <div className="notice">{search.llm_fallback}</div>}{search.results.length === 0 ? <div className="empty">没有找到可访问的主题帖。</div> : search.results.map(result => <article className="card" key={result.topic.id}><div className="card-head"><div><a href={result.topic.url} target="_blank" rel="noreferrer"><h3>{result.topic.title}</h3></a><p>{result.topic.board || '未知板块'} · {result.topic.published_at || '时间未知'} · {result.topic.reply_count ?? 0} 条回复</p></div><span className="score">{result.score.toFixed(1)}</span></div><p className="reason">{result.reason}</p>{result.evidence && <blockquote>{result.evidence}</blockquote>}</article>)}</section>}</>}
    {error && <div className="error" role="alert">{error}</div>}<footer>数据仅来自当前账号可访问的 CC98 内容；正文不会默认发送给外部服务。</footer></main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
